stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/ingested_data.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/ingested_data.csv
    outs:
      - data/preprocessed_data.csv

  model_training:
    cmd: python src/model_building.py
    deps:
      - src/model_building.py
      - data/preprocessed_data.csv
    outs:
      - models/scaler.pkl
      - models/xgb_model.pkl